class Constants{
  static const String appUserRef = 'app_users';

  static const String houseRef = 'houses';

  static const String estatesRef = 'estates';

  static const String activeCodeRef = 'active_codes';

  static const String deactivatedCodeRef = 'deactivated_codes';

  ///Minimum value that can be generated by the code generator 1000
  static const int min = 1000;

  ///Maximum value that can be generated by the code generator, max is always exclusive so the maximum is 9999
  static const int max = 10000;

  ///How long the each generated code takes before it expires
  static const Duration expirationDuration = Duration(hours: 12);
}